using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Tests.Migrations
{
    public partial class CreateDatabase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Continents",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Continents", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ContinentId = table.Column<int>(nullable: false),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Countries_Continents_ContinentId",
                        column: x => x.ContinentId,
                        principalTable: "Continents",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Continents",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Asia" },
                    { 2, "Africa" },
                    { 3, "North America" },
                    { 4, "South America" },
                    { 5, "Antarctica" },
                    { 6, "Europe" },
                    { 7, "Australia" },
                    { 8, "Oceania" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "ContinentId", "Name" },
                values: new object[,]
                {
                    { 4, 1, "Afghanistan, Islamic Republic of" },
                    { 68, 4, "Bolivia, Republic of" },
                    { 76, 4, "Brazil, Federative Republic of" },
                    { 152, 4, "Chile, Republic of" },
                    { 170, 4, "Colombia, Republic of" },
                    { 218, 4, "Ecuador, Republic of" },
                    { 238, 4, "Falkland Islands (Malvinas)" },
                    { 254, 4, "French Guiana" },
                    { 328, 4, "Guyana, Co-operative Republic of" },
                    { 600, 4, "Paraguay, Republic of" },
                    { 604, 4, "Peru, Republic of" },
                    { 740, 4, "Suriname, Republic of" },
                    { 858, 4, "Uruguay, Eastern Republic of" },
                    { 862, 4, "Venezuela, Bolivarian Republic of" },
                    { 10, 5, "Antarctica (the territory South of 60 deg S)" },
                    { 74, 5, "Bouvet Island (Bouvetoya)" },
                    { 239, 5, "South Georgia and the South Sandwich Islands" },
                    { 260, 5, "French Southern Territories" },
                    { 334, 5, "Heard Island and McDonald Islands" },
                    { 8, 6, "Albania, Republic of" },
                    { 20, 6, "Andorra, Principality of" },
                    { 40, 6, "Austria, Republic of" },
                    { 56, 6, "Belgium, Kingdom of" },
                    { 70, 6, "Bosnia and Herzegovina" },
                    { 100, 6, "Bulgaria, Republic of" },
                    { 112, 6, "Belarus, Republic of" },
                    { 191, 6, "Croatia, Republic of" },
                    { 203, 6, "Czech Republic" },
                    { 32, 4, "Argentina, Argentine Republic" },
                    { 208, 6, "Denmark, Kingdom of" },
                    { 850, 3, "United States Virgin Islands" },
                    { 796, 3, "Turks and Caicos Islands" },
                    { 304, 3, "Greenland" },
                    { 308, 3, "Grenada" },
                    { 312, 3, "Guadeloupe" },
                    { 320, 3, "Guatemala, Republic of" },
                    { 332, 3, "Haiti, Republic of" },
                    { 340, 3, "Honduras, Republic of" },
                    { 388, 3, "Jamaica" },
                    { 474, 3, "Martinique" },
                    { 484, 3, "Mexico, United Mexican States" },
                    { 500, 3, "Montserrat" },
                    { 530, 3, "Netherlands Antilles" },
                    { 531, 3, "CuraÃ§ao" },
                    { 533, 3, "Aruba" },
                    { 534, 3, "Sint Maarten (Netherlands)" },
                    { 535, 3, "Bonaire, Sint Eustatius and Saba" },
                    { 558, 3, "Nicaragua, Republic of" },
                    { 581, 3, "United States Minor Outlying Islands" },
                    { 591, 3, "Panama, Republic of" },
                    { 630, 3, "Puerto Rico, Commonwealth of" },
                    { 652, 3, "Saint Barthelemy" },
                    { 659, 3, "Saint Kitts and Nevis, Federation of" },
                    { 660, 3, "Anguilla" },
                    { 662, 3, "Saint Lucia" },
                    { 663, 3, "Saint Martin" },
                    { 666, 3, "Saint Pierre and Miquelon" },
                    { 670, 3, "Saint Vincent and the Grenadines" },
                    { 780, 3, "Trinidad and Tobago, Republic of" },
                    { 840, 3, "United States of America" },
                    { 233, 6, "Estonia, Republic of" },
                    { 234, 6, "Faroe Islands" },
                    { 246, 6, "Finland, Republic of" },
                    { 826, 6, "United Kingdom of Great Britain & Northern Ireland" },
                    { 831, 6, "Guernsey, Bailiwick of" },
                    { 832, 6, "Jersey, Bailiwick of" },
                    { 833, 6, "Isle of Man" },
                    { 16, 8, "American Samoa" },
                    { 36, 8, "Australia, Commonwealth of" },
                    { 90, 8, "Solomon Islands" },
                    { 184, 8, "Cook Islands" },
                    { 242, 8, "Fiji, Republic of the Fiji Islands" },
                    { 258, 8, "French Polynesia" },
                    { 296, 8, "Kiribati, Republic of" },
                    { 316, 8, "Guam" },
                    { 520, 8, "Nauru, Republic of" },
                    { 540, 8, "New Caledonia" },
                    { 548, 8, "Vanuatu, Republic of" },
                    { 554, 8, "New Zealand" },
                    { 570, 8, "Niue" },
                    { 574, 8, "Norfolk Island" },
                    { 580, 8, "Northern Mariana Islands, Commonwealth of the" },
                    { 583, 8, "Micronesia, Federated States of" },
                    { 584, 8, "Marshall Islands, Republic of the" },
                    { 585, 8, "Palau, Republic of" },
                    { 598, 8, "Papua New Guinea, Independent State of" },
                    { 612, 8, "Pitcairn Islands" },
                    { 772, 8, "Tokelau" },
                    { 776, 8, "Tonga, Kingdom of" },
                    { 798, 8, "Tuvalu" },
                    { 807, 6, "Macedonia, The Former Yugoslav Republic of" },
                    { 804, 6, "Ukraine" },
                    { 756, 6, "Switzerland, Swiss Confederation" },
                    { 752, 6, "Sweden, Kingdom of" },
                    { 250, 6, "France, French Republic" },
                    { 276, 6, "Germany, Federal Republic of" },
                    { 292, 6, "Gibraltar" },
                    { 300, 6, "Greece, Hellenic Republic" },
                    { 336, 6, "Holy See (Vatican City State)" },
                    { 348, 6, "Hungary, Republic of" },
                    { 352, 6, "Iceland, Republic of" },
                    { 372, 6, "Ireland" },
                    { 380, 6, "Italy, Italian Republic" },
                    { 428, 6, "Latvia, Republic of" },
                    { 438, 6, "Liechtenstein, Principality of" },
                    { 440, 6, "Lithuania, Republic of" },
                    { 442, 6, "Luxembourg, Grand Duchy of" },
                    { 222, 3, "El Salvador, Republic of" },
                    { 470, 6, "Malta, Republic of" },
                    { 498, 6, "Moldova, Republic of" },
                    { 499, 6, "Montenegro, Republic of" },
                    { 528, 6, "Netherlands, Kingdom of the" },
                    { 578, 6, "Norway, Kingdom of" },
                    { 616, 6, "Poland, Republic of" },
                    { 620, 6, "Portugal, Portuguese Republic" },
                    { 642, 6, "Romania" },
                    { 674, 6, "San Marino, Republic of" },
                    { 688, 6, "Serbia, Republic of" },
                    { 703, 6, "Slovakia (Slovak Republic)" },
                    { 705, 6, "Slovenia, Republic of" },
                    { 724, 6, "Spain, Kingdom of" },
                    { 744, 6, "Svalbard & Jan Mayen Islands" },
                    { 492, 6, "Monaco, Principality of" },
                    { 876, 8, "Wallis and Futuna" },
                    { 214, 3, "Dominican Republic" },
                    { 192, 3, "Cuba, Republic of" },
                    { 422, 1, "Lebanon, Lebanese Republic" },
                    { 446, 1, "Macao, Special Administrative Region of China" },
                    { 458, 1, "Malaysia" },
                    { 462, 1, "Maldives, Republic of" },
                    { 496, 1, "Mongolia" },
                    { 512, 1, "Oman, Sultanate of" },
                    { 524, 1, "Nepal, State of" },
                    { 586, 1, "Pakistan, Islamic Republic of" },
                    { 608, 1, "Philippines, Republic of the" },
                    { 626, 1, "Timor-Leste, Democratic Republic of" },
                    { 634, 1, "Qatar, State of" },
                    { 643, 1, "Russian Federation" },
                    { 682, 1, "Saudi Arabia, Kingdom of" },
                    { 702, 1, "Singapore, Republic of" },
                    { 704, 1, "Vietnam, Socialist Republic of" },
                    { 760, 1, "Syrian Arab Republic" },
                    { 762, 1, "Tajikistan, Republic of" },
                    { 764, 1, "Thailand, Kingdom of" },
                    { 784, 1, "United Arab Emirates" },
                    { 792, 1, "Turkey, Republic of" },
                    { 795, 1, "Turkmenistan" },
                    { 860, 1, "Uzbekistan, Republic of" },
                    { 887, 1, "Yemen" },
                    { 12, 2, "Algeria, People's Democratic Republic of" },
                    { 24, 2, "Angola, Republic of" },
                    { 72, 2, "Botswana, Republic of" },
                    { 108, 2, "Burundi, Republic of" },
                    { 418, 1, "Lao People's Democratic Republic" },
                    { 120, 2, "Cameroon, Republic of" },
                    { 417, 1, "Kyrgyz Republic" },
                    { 410, 1, "Korea, Republic of" },
                    { 31, 1, "Azerbaijan, Republic of" },
                    { 48, 1, "Bahrain, Kingdom of" },
                    { 50, 1, "Bangladesh, People's Republic of" },
                    { 51, 1, "Armenia, Republic of" },
                    { 64, 1, "Bhutan, Kingdom of" },
                    { 86, 1, "British Indian Ocean Territory (Chagos Archipelago)" },
                    { 96, 1, "Brunei Darussalam" },
                    { 104, 1, "Myanmar, Union of" },
                    { 116, 1, "Cambodia, Kingdom of" },
                    { 144, 1, "Sri Lanka, Democratic Socialist Republic of" },
                    { 156, 1, "China, People's Republic of" },
                    { 158, 1, "Taiwan" },
                    { 162, 1, "Christmas Island" },
                    { 166, 1, "Cocos (Keeling) Islands" },
                    { 196, 1, "Cyprus, Republic of" },
                    { 268, 1, "Georgia" },
                    { 275, 1, "Palestinian Territory, Occupied" },
                    { 344, 1, "Hong Kong, Special Administrative Region of China" },
                    { 356, 1, "India, Republic of" },
                    { 360, 1, "Indonesia, Republic of" },
                    { 364, 1, "Iran, Islamic Republic of" },
                    { 368, 1, "Iraq, Republic of" },
                    { 376, 1, "Israel, State of" },
                    { 392, 1, "Japan" },
                    { 398, 1, "Kazakhstan, Republic of" },
                    { 400, 1, "Jordan, Hashemite Kingdom of" },
                    { 408, 1, "Korea, Democratic People's Republic of" },
                    { 414, 1, "Kuwait, State of" },
                    { 132, 2, "Cape Verde, Republic of" },
                    { 140, 2, "Central African Republic" },
                    { 148, 2, "Chad, Republic of" },
                    { 678, 2, "Sao Tome and Principe, Democratic Republic of" },
                    { 686, 2, "Senegal, Republic of" },
                    { 690, 2, "Seychelles, Republic of" },
                    { 694, 2, "Sierra Leone, Republic of" },
                    { 706, 2, "Somalia, Somali Republic" },
                    { 710, 2, "South Africa, Republic of" },
                    { 716, 2, "Zimbabwe, Republic of" },
                    { 728, 2, "South Sudan" },
                    { 732, 2, "Western Sahara" },
                    { 736, 2, "Sudan, Republic of" },
                    { 748, 2, "Swaziland, Kingdom of" },
                    { 768, 2, "Togo, Togolese Republic" },
                    { 788, 2, "Tunisia, Tunisian Republic" },
                    { 800, 2, "Uganda, Republic of" },
                    { 818, 2, "Egypt, Arab Republic of" },
                    { 834, 2, "Tanzania, United Republic of" },
                    { 854, 2, "Burkina Faso" },
                    { 894, 2, "Zambia, Republic of" },
                    { 28, 3, "Antigua and Barbuda" },
                    { 44, 3, "Bahamas, Commonwealth of the" },
                    { 52, 3, "Barbados" },
                    { 60, 3, "Bermuda" },
                    { 84, 3, "Belize" },
                    { 92, 3, "British Virgin Islands" },
                    { 124, 3, "Canada" },
                    { 136, 3, "Cayman Islands" },
                    { 188, 3, "Costa Rica, Republic of" },
                    { 654, 2, "Saint Helena" },
                    { 646, 2, "Rwanda, Republic of" },
                    { 638, 2, "Reunion" },
                    { 624, 2, "Guinea-Bissau, Republic of" },
                    { 174, 2, "Comoros, Union of the" },
                    { 175, 2, "Mayotte" },
                    { 178, 2, "Congo, Republic of the" },
                    { 180, 2, "Congo, Democratic Republic of the" },
                    { 204, 2, "Benin, Republic of" },
                    { 226, 2, "Equatorial Guinea, Republic of" },
                    { 231, 2, "Ethiopia, Federal Democratic Republic of" },
                    { 232, 2, "Eritrea, State of" },
                    { 262, 2, "Djibouti, Republic of" },
                    { 266, 2, "Gabon, Gabonese Republic" },
                    { 270, 2, "Gambia, Republic of the" },
                    { 288, 2, "Ghana, Republic of" },
                    { 324, 2, "Guinea, Republic of" },
                    { 212, 3, "Dominica, Commonwealth of" },
                    { 384, 2, "Cote d'Ivoire, Republic of" },
                    { 426, 2, "Lesotho, Kingdom of" },
                    { 430, 2, "Liberia, Republic of" },
                    { 434, 2, "Libyan Arab Jamahiriya" },
                    { 450, 2, "Madagascar, Republic of" },
                    { 454, 2, "Malawi, Republic of" },
                    { 466, 2, "Mali, Republic of" },
                    { 478, 2, "Mauritania, Islamic Republic of" },
                    { 480, 2, "Mauritius, Republic of" },
                    { 504, 2, "Morocco, Kingdom of" },
                    { 508, 2, "Mozambique, Republic of" },
                    { 516, 2, "Namibia, Republic of" },
                    { 562, 2, "Niger, Republic of" },
                    { 566, 2, "Nigeria, Federal Republic of" },
                    { 404, 2, "Kenya, Republic of" },
                    { 882, 8, "Samoa, Independent State of" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Countries_ContinentId",
                table: "Countries",
                column: "ContinentId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.DropTable(
                name: "Continents");
        }
    }
}
