// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tests.Data;

namespace Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tests.Data.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 4,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Oceania"
                        });
                });

            modelBuilder.Entity("Tests.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            ContinentId = 1,
                            Name = "Afghanistan, Islamic Republic of"
                        },
                        new
                        {
                            Id = 8,
                            ContinentId = 6,
                            Name = "Albania, Republic of"
                        },
                        new
                        {
                            Id = 10,
                            ContinentId = 5,
                            Name = "Antarctica (the territory South of 60 deg S)"
                        },
                        new
                        {
                            Id = 12,
                            ContinentId = 2,
                            Name = "Algeria, People's Democratic Republic of"
                        },
                        new
                        {
                            Id = 16,
                            ContinentId = 8,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 20,
                            ContinentId = 6,
                            Name = "Andorra, Principality of"
                        },
                        new
                        {
                            Id = 24,
                            ContinentId = 2,
                            Name = "Angola, Republic of"
                        },
                        new
                        {
                            Id = 28,
                            ContinentId = 3,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 31,
                            ContinentId = 1,
                            Name = "Azerbaijan, Republic of"
                        },
                        new
                        {
                            Id = 32,
                            ContinentId = 4,
                            Name = "Argentina, Argentine Republic"
                        },
                        new
                        {
                            Id = 36,
                            ContinentId = 8,
                            Name = "Australia, Commonwealth of"
                        },
                        new
                        {
                            Id = 40,
                            ContinentId = 6,
                            Name = "Austria, Republic of"
                        },
                        new
                        {
                            Id = 44,
                            ContinentId = 3,
                            Name = "Bahamas, Commonwealth of the"
                        },
                        new
                        {
                            Id = 48,
                            ContinentId = 1,
                            Name = "Bahrain, Kingdom of"
                        },
                        new
                        {
                            Id = 50,
                            ContinentId = 1,
                            Name = "Bangladesh, People's Republic of"
                        },
                        new
                        {
                            Id = 51,
                            ContinentId = 1,
                            Name = "Armenia, Republic of"
                        },
                        new
                        {
                            Id = 52,
                            ContinentId = 3,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 56,
                            ContinentId = 6,
                            Name = "Belgium, Kingdom of"
                        },
                        new
                        {
                            Id = 60,
                            ContinentId = 3,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 64,
                            ContinentId = 1,
                            Name = "Bhutan, Kingdom of"
                        },
                        new
                        {
                            Id = 68,
                            ContinentId = 4,
                            Name = "Bolivia, Republic of"
                        },
                        new
                        {
                            Id = 70,
                            ContinentId = 6,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 72,
                            ContinentId = 2,
                            Name = "Botswana, Republic of"
                        },
                        new
                        {
                            Id = 74,
                            ContinentId = 5,
                            Name = "Bouvet Island (Bouvetoya)"
                        },
                        new
                        {
                            Id = 76,
                            ContinentId = 4,
                            Name = "Brazil, Federative Republic of"
                        },
                        new
                        {
                            Id = 84,
                            ContinentId = 3,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 86,
                            ContinentId = 1,
                            Name = "British Indian Ocean Territory (Chagos Archipelago)"
                        },
                        new
                        {
                            Id = 90,
                            ContinentId = 8,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 92,
                            ContinentId = 3,
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 96,
                            ContinentId = 1,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 100,
                            ContinentId = 6,
                            Name = "Bulgaria, Republic of"
                        },
                        new
                        {
                            Id = 104,
                            ContinentId = 1,
                            Name = "Myanmar, Union of"
                        },
                        new
                        {
                            Id = 108,
                            ContinentId = 2,
                            Name = "Burundi, Republic of"
                        },
                        new
                        {
                            Id = 112,
                            ContinentId = 6,
                            Name = "Belarus, Republic of"
                        },
                        new
                        {
                            Id = 116,
                            ContinentId = 1,
                            Name = "Cambodia, Kingdom of"
                        },
                        new
                        {
                            Id = 120,
                            ContinentId = 2,
                            Name = "Cameroon, Republic of"
                        },
                        new
                        {
                            Id = 124,
                            ContinentId = 3,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 132,
                            ContinentId = 2,
                            Name = "Cape Verde, Republic of"
                        },
                        new
                        {
                            Id = 136,
                            ContinentId = 3,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 140,
                            ContinentId = 2,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 144,
                            ContinentId = 1,
                            Name = "Sri Lanka, Democratic Socialist Republic of"
                        },
                        new
                        {
                            Id = 148,
                            ContinentId = 2,
                            Name = "Chad, Republic of"
                        },
                        new
                        {
                            Id = 152,
                            ContinentId = 4,
                            Name = "Chile, Republic of"
                        },
                        new
                        {
                            Id = 156,
                            ContinentId = 1,
                            Name = "China, People's Republic of"
                        },
                        new
                        {
                            Id = 158,
                            ContinentId = 1,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 162,
                            ContinentId = 1,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 166,
                            ContinentId = 1,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 170,
                            ContinentId = 4,
                            Name = "Colombia, Republic of"
                        },
                        new
                        {
                            Id = 174,
                            ContinentId = 2,
                            Name = "Comoros, Union of the"
                        },
                        new
                        {
                            Id = 175,
                            ContinentId = 2,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 178,
                            ContinentId = 2,
                            Name = "Congo, Republic of the"
                        },
                        new
                        {
                            Id = 180,
                            ContinentId = 2,
                            Name = "Congo, Democratic Republic of the"
                        },
                        new
                        {
                            Id = 184,
                            ContinentId = 8,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 188,
                            ContinentId = 3,
                            Name = "Costa Rica, Republic of"
                        },
                        new
                        {
                            Id = 191,
                            ContinentId = 6,
                            Name = "Croatia, Republic of"
                        },
                        new
                        {
                            Id = 192,
                            ContinentId = 3,
                            Name = "Cuba, Republic of"
                        },
                        new
                        {
                            Id = 196,
                            ContinentId = 1,
                            Name = "Cyprus, Republic of"
                        },
                        new
                        {
                            Id = 203,
                            ContinentId = 6,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 204,
                            ContinentId = 2,
                            Name = "Benin, Republic of"
                        },
                        new
                        {
                            Id = 208,
                            ContinentId = 6,
                            Name = "Denmark, Kingdom of"
                        },
                        new
                        {
                            Id = 212,
                            ContinentId = 3,
                            Name = "Dominica, Commonwealth of"
                        },
                        new
                        {
                            Id = 214,
                            ContinentId = 3,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 218,
                            ContinentId = 4,
                            Name = "Ecuador, Republic of"
                        },
                        new
                        {
                            Id = 222,
                            ContinentId = 3,
                            Name = "El Salvador, Republic of"
                        },
                        new
                        {
                            Id = 226,
                            ContinentId = 2,
                            Name = "Equatorial Guinea, Republic of"
                        },
                        new
                        {
                            Id = 231,
                            ContinentId = 2,
                            Name = "Ethiopia, Federal Democratic Republic of"
                        },
                        new
                        {
                            Id = 232,
                            ContinentId = 2,
                            Name = "Eritrea, State of"
                        },
                        new
                        {
                            Id = 233,
                            ContinentId = 6,
                            Name = "Estonia, Republic of"
                        },
                        new
                        {
                            Id = 234,
                            ContinentId = 6,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 238,
                            ContinentId = 4,
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 239,
                            ContinentId = 5,
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 242,
                            ContinentId = 8,
                            Name = "Fiji, Republic of the Fiji Islands"
                        },
                        new
                        {
                            Id = 246,
                            ContinentId = 6,
                            Name = "Finland, Republic of"
                        },
                        new
                        {
                            Id = 250,
                            ContinentId = 6,
                            Name = "France, French Republic"
                        },
                        new
                        {
                            Id = 254,
                            ContinentId = 4,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 258,
                            ContinentId = 8,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 260,
                            ContinentId = 5,
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 262,
                            ContinentId = 2,
                            Name = "Djibouti, Republic of"
                        },
                        new
                        {
                            Id = 266,
                            ContinentId = 2,
                            Name = "Gabon, Gabonese Republic"
                        },
                        new
                        {
                            Id = 268,
                            ContinentId = 1,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 270,
                            ContinentId = 2,
                            Name = "Gambia, Republic of the"
                        },
                        new
                        {
                            Id = 275,
                            ContinentId = 1,
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 276,
                            ContinentId = 6,
                            Name = "Germany, Federal Republic of"
                        },
                        new
                        {
                            Id = 288,
                            ContinentId = 2,
                            Name = "Ghana, Republic of"
                        },
                        new
                        {
                            Id = 292,
                            ContinentId = 6,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 296,
                            ContinentId = 8,
                            Name = "Kiribati, Republic of"
                        },
                        new
                        {
                            Id = 300,
                            ContinentId = 6,
                            Name = "Greece, Hellenic Republic"
                        },
                        new
                        {
                            Id = 304,
                            ContinentId = 3,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 308,
                            ContinentId = 3,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 312,
                            ContinentId = 3,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 316,
                            ContinentId = 8,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 320,
                            ContinentId = 3,
                            Name = "Guatemala, Republic of"
                        },
                        new
                        {
                            Id = 324,
                            ContinentId = 2,
                            Name = "Guinea, Republic of"
                        },
                        new
                        {
                            Id = 328,
                            ContinentId = 4,
                            Name = "Guyana, Co-operative Republic of"
                        },
                        new
                        {
                            Id = 332,
                            ContinentId = 3,
                            Name = "Haiti, Republic of"
                        },
                        new
                        {
                            Id = 334,
                            ContinentId = 5,
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 336,
                            ContinentId = 6,
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 340,
                            ContinentId = 3,
                            Name = "Honduras, Republic of"
                        },
                        new
                        {
                            Id = 344,
                            ContinentId = 1,
                            Name = "Hong Kong, Special Administrative Region of China"
                        },
                        new
                        {
                            Id = 348,
                            ContinentId = 6,
                            Name = "Hungary, Republic of"
                        },
                        new
                        {
                            Id = 352,
                            ContinentId = 6,
                            Name = "Iceland, Republic of"
                        },
                        new
                        {
                            Id = 356,
                            ContinentId = 1,
                            Name = "India, Republic of"
                        },
                        new
                        {
                            Id = 360,
                            ContinentId = 1,
                            Name = "Indonesia, Republic of"
                        },
                        new
                        {
                            Id = 364,
                            ContinentId = 1,
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 368,
                            ContinentId = 1,
                            Name = "Iraq, Republic of"
                        },
                        new
                        {
                            Id = 372,
                            ContinentId = 6,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 376,
                            ContinentId = 1,
                            Name = "Israel, State of"
                        },
                        new
                        {
                            Id = 380,
                            ContinentId = 6,
                            Name = "Italy, Italian Republic"
                        },
                        new
                        {
                            Id = 384,
                            ContinentId = 2,
                            Name = "Cote d'Ivoire, Republic of"
                        },
                        new
                        {
                            Id = 388,
                            ContinentId = 3,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 392,
                            ContinentId = 1,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 398,
                            ContinentId = 1,
                            Name = "Kazakhstan, Republic of"
                        },
                        new
                        {
                            Id = 400,
                            ContinentId = 1,
                            Name = "Jordan, Hashemite Kingdom of"
                        },
                        new
                        {
                            Id = 404,
                            ContinentId = 2,
                            Name = "Kenya, Republic of"
                        },
                        new
                        {
                            Id = 408,
                            ContinentId = 1,
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 410,
                            ContinentId = 1,
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 414,
                            ContinentId = 1,
                            Name = "Kuwait, State of"
                        },
                        new
                        {
                            Id = 417,
                            ContinentId = 1,
                            Name = "Kyrgyz Republic"
                        },
                        new
                        {
                            Id = 418,
                            ContinentId = 1,
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 422,
                            ContinentId = 1,
                            Name = "Lebanon, Lebanese Republic"
                        },
                        new
                        {
                            Id = 426,
                            ContinentId = 2,
                            Name = "Lesotho, Kingdom of"
                        },
                        new
                        {
                            Id = 428,
                            ContinentId = 6,
                            Name = "Latvia, Republic of"
                        },
                        new
                        {
                            Id = 430,
                            ContinentId = 2,
                            Name = "Liberia, Republic of"
                        },
                        new
                        {
                            Id = 434,
                            ContinentId = 2,
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 438,
                            ContinentId = 6,
                            Name = "Liechtenstein, Principality of"
                        },
                        new
                        {
                            Id = 440,
                            ContinentId = 6,
                            Name = "Lithuania, Republic of"
                        },
                        new
                        {
                            Id = 442,
                            ContinentId = 6,
                            Name = "Luxembourg, Grand Duchy of"
                        },
                        new
                        {
                            Id = 446,
                            ContinentId = 1,
                            Name = "Macao, Special Administrative Region of China"
                        },
                        new
                        {
                            Id = 450,
                            ContinentId = 2,
                            Name = "Madagascar, Republic of"
                        },
                        new
                        {
                            Id = 454,
                            ContinentId = 2,
                            Name = "Malawi, Republic of"
                        },
                        new
                        {
                            Id = 458,
                            ContinentId = 1,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 462,
                            ContinentId = 1,
                            Name = "Maldives, Republic of"
                        },
                        new
                        {
                            Id = 466,
                            ContinentId = 2,
                            Name = "Mali, Republic of"
                        },
                        new
                        {
                            Id = 470,
                            ContinentId = 6,
                            Name = "Malta, Republic of"
                        },
                        new
                        {
                            Id = 474,
                            ContinentId = 3,
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 478,
                            ContinentId = 2,
                            Name = "Mauritania, Islamic Republic of"
                        },
                        new
                        {
                            Id = 480,
                            ContinentId = 2,
                            Name = "Mauritius, Republic of"
                        },
                        new
                        {
                            Id = 484,
                            ContinentId = 3,
                            Name = "Mexico, United Mexican States"
                        },
                        new
                        {
                            Id = 492,
                            ContinentId = 6,
                            Name = "Monaco, Principality of"
                        },
                        new
                        {
                            Id = 496,
                            ContinentId = 1,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 498,
                            ContinentId = 6,
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 499,
                            ContinentId = 6,
                            Name = "Montenegro, Republic of"
                        },
                        new
                        {
                            Id = 500,
                            ContinentId = 3,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 504,
                            ContinentId = 2,
                            Name = "Morocco, Kingdom of"
                        },
                        new
                        {
                            Id = 508,
                            ContinentId = 2,
                            Name = "Mozambique, Republic of"
                        },
                        new
                        {
                            Id = 512,
                            ContinentId = 1,
                            Name = "Oman, Sultanate of"
                        },
                        new
                        {
                            Id = 516,
                            ContinentId = 2,
                            Name = "Namibia, Republic of"
                        },
                        new
                        {
                            Id = 520,
                            ContinentId = 8,
                            Name = "Nauru, Republic of"
                        },
                        new
                        {
                            Id = 524,
                            ContinentId = 1,
                            Name = "Nepal, State of"
                        },
                        new
                        {
                            Id = 528,
                            ContinentId = 6,
                            Name = "Netherlands, Kingdom of the"
                        },
                        new
                        {
                            Id = 530,
                            ContinentId = 3,
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 531,
                            ContinentId = 3,
                            Name = "CuraÃ§ao"
                        },
                        new
                        {
                            Id = 533,
                            ContinentId = 3,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 534,
                            ContinentId = 3,
                            Name = "Sint Maarten (Netherlands)"
                        },
                        new
                        {
                            Id = 535,
                            ContinentId = 3,
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 540,
                            ContinentId = 8,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 548,
                            ContinentId = 8,
                            Name = "Vanuatu, Republic of"
                        },
                        new
                        {
                            Id = 554,
                            ContinentId = 8,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 558,
                            ContinentId = 3,
                            Name = "Nicaragua, Republic of"
                        },
                        new
                        {
                            Id = 562,
                            ContinentId = 2,
                            Name = "Niger, Republic of"
                        },
                        new
                        {
                            Id = 566,
                            ContinentId = 2,
                            Name = "Nigeria, Federal Republic of"
                        },
                        new
                        {
                            Id = 570,
                            ContinentId = 8,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 574,
                            ContinentId = 8,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 578,
                            ContinentId = 6,
                            Name = "Norway, Kingdom of"
                        },
                        new
                        {
                            Id = 580,
                            ContinentId = 8,
                            Name = "Northern Mariana Islands, Commonwealth of the"
                        },
                        new
                        {
                            Id = 581,
                            ContinentId = 3,
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 583,
                            ContinentId = 8,
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 584,
                            ContinentId = 8,
                            Name = "Marshall Islands, Republic of the"
                        },
                        new
                        {
                            Id = 585,
                            ContinentId = 8,
                            Name = "Palau, Republic of"
                        },
                        new
                        {
                            Id = 586,
                            ContinentId = 1,
                            Name = "Pakistan, Islamic Republic of"
                        },
                        new
                        {
                            Id = 591,
                            ContinentId = 3,
                            Name = "Panama, Republic of"
                        },
                        new
                        {
                            Id = 598,
                            ContinentId = 8,
                            Name = "Papua New Guinea, Independent State of"
                        },
                        new
                        {
                            Id = 600,
                            ContinentId = 4,
                            Name = "Paraguay, Republic of"
                        },
                        new
                        {
                            Id = 604,
                            ContinentId = 4,
                            Name = "Peru, Republic of"
                        },
                        new
                        {
                            Id = 608,
                            ContinentId = 1,
                            Name = "Philippines, Republic of the"
                        },
                        new
                        {
                            Id = 612,
                            ContinentId = 8,
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 616,
                            ContinentId = 6,
                            Name = "Poland, Republic of"
                        },
                        new
                        {
                            Id = 620,
                            ContinentId = 6,
                            Name = "Portugal, Portuguese Republic"
                        },
                        new
                        {
                            Id = 624,
                            ContinentId = 2,
                            Name = "Guinea-Bissau, Republic of"
                        },
                        new
                        {
                            Id = 626,
                            ContinentId = 1,
                            Name = "Timor-Leste, Democratic Republic of"
                        },
                        new
                        {
                            Id = 630,
                            ContinentId = 3,
                            Name = "Puerto Rico, Commonwealth of"
                        },
                        new
                        {
                            Id = 634,
                            ContinentId = 1,
                            Name = "Qatar, State of"
                        },
                        new
                        {
                            Id = 638,
                            ContinentId = 2,
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 642,
                            ContinentId = 6,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 643,
                            ContinentId = 1,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 646,
                            ContinentId = 2,
                            Name = "Rwanda, Republic of"
                        },
                        new
                        {
                            Id = 652,
                            ContinentId = 3,
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = 654,
                            ContinentId = 2,
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 659,
                            ContinentId = 3,
                            Name = "Saint Kitts and Nevis, Federation of"
                        },
                        new
                        {
                            Id = 660,
                            ContinentId = 3,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 662,
                            ContinentId = 3,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 663,
                            ContinentId = 3,
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 666,
                            ContinentId = 3,
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 670,
                            ContinentId = 3,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 674,
                            ContinentId = 6,
                            Name = "San Marino, Republic of"
                        },
                        new
                        {
                            Id = 678,
                            ContinentId = 2,
                            Name = "Sao Tome and Principe, Democratic Republic of"
                        },
                        new
                        {
                            Id = 682,
                            ContinentId = 1,
                            Name = "Saudi Arabia, Kingdom of"
                        },
                        new
                        {
                            Id = 686,
                            ContinentId = 2,
                            Name = "Senegal, Republic of"
                        },
                        new
                        {
                            Id = 688,
                            ContinentId = 6,
                            Name = "Serbia, Republic of"
                        },
                        new
                        {
                            Id = 690,
                            ContinentId = 2,
                            Name = "Seychelles, Republic of"
                        },
                        new
                        {
                            Id = 694,
                            ContinentId = 2,
                            Name = "Sierra Leone, Republic of"
                        },
                        new
                        {
                            Id = 702,
                            ContinentId = 1,
                            Name = "Singapore, Republic of"
                        },
                        new
                        {
                            Id = 703,
                            ContinentId = 6,
                            Name = "Slovakia (Slovak Republic)"
                        },
                        new
                        {
                            Id = 704,
                            ContinentId = 1,
                            Name = "Vietnam, Socialist Republic of"
                        },
                        new
                        {
                            Id = 705,
                            ContinentId = 6,
                            Name = "Slovenia, Republic of"
                        },
                        new
                        {
                            Id = 706,
                            ContinentId = 2,
                            Name = "Somalia, Somali Republic"
                        },
                        new
                        {
                            Id = 710,
                            ContinentId = 2,
                            Name = "South Africa, Republic of"
                        },
                        new
                        {
                            Id = 716,
                            ContinentId = 2,
                            Name = "Zimbabwe, Republic of"
                        },
                        new
                        {
                            Id = 724,
                            ContinentId = 6,
                            Name = "Spain, Kingdom of"
                        },
                        new
                        {
                            Id = 728,
                            ContinentId = 2,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 732,
                            ContinentId = 2,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 736,
                            ContinentId = 2,
                            Name = "Sudan, Republic of"
                        },
                        new
                        {
                            Id = 740,
                            ContinentId = 4,
                            Name = "Suriname, Republic of"
                        },
                        new
                        {
                            Id = 744,
                            ContinentId = 6,
                            Name = "Svalbard & Jan Mayen Islands"
                        },
                        new
                        {
                            Id = 748,
                            ContinentId = 2,
                            Name = "Swaziland, Kingdom of"
                        },
                        new
                        {
                            Id = 752,
                            ContinentId = 6,
                            Name = "Sweden, Kingdom of"
                        },
                        new
                        {
                            Id = 756,
                            ContinentId = 6,
                            Name = "Switzerland, Swiss Confederation"
                        },
                        new
                        {
                            Id = 760,
                            ContinentId = 1,
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 762,
                            ContinentId = 1,
                            Name = "Tajikistan, Republic of"
                        },
                        new
                        {
                            Id = 764,
                            ContinentId = 1,
                            Name = "Thailand, Kingdom of"
                        },
                        new
                        {
                            Id = 768,
                            ContinentId = 2,
                            Name = "Togo, Togolese Republic"
                        },
                        new
                        {
                            Id = 772,
                            ContinentId = 8,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 776,
                            ContinentId = 8,
                            Name = "Tonga, Kingdom of"
                        },
                        new
                        {
                            Id = 780,
                            ContinentId = 3,
                            Name = "Trinidad and Tobago, Republic of"
                        },
                        new
                        {
                            Id = 784,
                            ContinentId = 1,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 788,
                            ContinentId = 2,
                            Name = "Tunisia, Tunisian Republic"
                        },
                        new
                        {
                            Id = 792,
                            ContinentId = 1,
                            Name = "Turkey, Republic of"
                        },
                        new
                        {
                            Id = 795,
                            ContinentId = 1,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 796,
                            ContinentId = 3,
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 798,
                            ContinentId = 8,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 800,
                            ContinentId = 2,
                            Name = "Uganda, Republic of"
                        },
                        new
                        {
                            Id = 804,
                            ContinentId = 6,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 807,
                            ContinentId = 6,
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 818,
                            ContinentId = 2,
                            Name = "Egypt, Arab Republic of"
                        },
                        new
                        {
                            Id = 826,
                            ContinentId = 6,
                            Name = "United Kingdom of Great Britain & Northern Ireland"
                        },
                        new
                        {
                            Id = 831,
                            ContinentId = 6,
                            Name = "Guernsey, Bailiwick of"
                        },
                        new
                        {
                            Id = 832,
                            ContinentId = 6,
                            Name = "Jersey, Bailiwick of"
                        },
                        new
                        {
                            Id = 833,
                            ContinentId = 6,
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 834,
                            ContinentId = 2,
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 840,
                            ContinentId = 3,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 850,
                            ContinentId = 3,
                            Name = "United States Virgin Islands"
                        },
                        new
                        {
                            Id = 854,
                            ContinentId = 2,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 858,
                            ContinentId = 4,
                            Name = "Uruguay, Eastern Republic of"
                        },
                        new
                        {
                            Id = 860,
                            ContinentId = 1,
                            Name = "Uzbekistan, Republic of"
                        },
                        new
                        {
                            Id = 862,
                            ContinentId = 4,
                            Name = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            Id = 876,
                            ContinentId = 8,
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 882,
                            ContinentId = 8,
                            Name = "Samoa, Independent State of"
                        },
                        new
                        {
                            Id = 887,
                            ContinentId = 1,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 894,
                            ContinentId = 2,
                            Name = "Zambia, Republic of"
                        });
                });

            modelBuilder.Entity("Tests.Data.Country", b =>
                {
                    b.HasOne("Tests.Data.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
